version: 2

sources:
    - name: staging
      #For bigquery:
      database: dtc-de-project-344607

      # For postgres:
      # database: production

      schema: br_properties_data_all

      # loaded_at_field: record_loaded_at
      tables:
        - name: sell_data_partitioned
        # - name: yellow_tripdata_external_table
        # - name: fhv_tripdata_external_table
         # freshness:
           # error_after: {count: 6, period: hour}

models:
    - name: stg_sell_properti_data
      description: >
        Properti sold data
